In [1]:
import numpy as np
import cv2
from scipy.spatial import distance
import utm

In [24]:
raw_pgm = cv2.imread("/home/ncslaber/hector_path_all_mm.pgm")
print(type(raw_pgm))

<class 'numpy.ndarray'>


In [4]:
raw_pgm[raw_pgm == 205]=255

In [7]:
distance.euclidean((0,0),(1,0))

1.0

In [10]:
a = np.array([5,5])
a / 5

array([1., 1.])

In [17]:
lat = 25.0821685
lng = 121.60401633333

In [18]:

from pyproj import Proj
_, _, zone, _ = utm.from_latlon(lat, lng)
proj = Proj(proj='utm', zone=zone, ellps='WGS84', preserve_units=False)

In [14]:
proj

<Other Coordinate Operation Transformer: utm>
Description: PROJ-based coordinate operation
Area of Use:
- undefined

In [15]:
ux, uy = proj(lng, lat)

In [18]:
ux

359216.53688289993

In [19]:
uy

2774773.3391035083

In [20]:
zone

51

In [24]:
utm.to_latlon(359216.536882, 2774773.339, 51, 'R')

lat = 25.0821685
lng = 121.60401633333

(25.082168499872612, 121.60401633332765)

In [25]:
utm.from_latlon(lat, lng)

(359216.53688264405, 2774773.339087446, 51, 'R')

In [26]:
4819-4773

118

In [4]:
raw_pgm = np.rot90(raw_pgm)

In [25]:
a = np.logical_or(raw_pgm==205,raw_pgm==255)
a = np.logical_or(a,raw_pgm==0)

In [26]:
raw_pgm[~a]

array([254, 254, 254, ..., 254, 254, 254], dtype=uint8)

In [8]:
"{:.2f},{:.2f}".format(lat,lng)

'25.08,121.60'

In [9]:
centroid_rawList = [1,2,3]

In [10]:
centroid_rawList.pop(0)

1

In [12]:
distance.euclidean(np.asarray([180.0 ,528.0]), np.asarray([148.0, 540.0]))

34.17601498127012

In [16]:
np.save('/home/ncslaber/lat_lon',[25.0821685, 121.60401633333])

In [23]:
neg_bd = np.array([[359209.8368829,2774776.63910351],[359210.8368829,2774777.63910351],[359209.8368829,2774777.63910351]])

In [24]:
gps_x, gps_y = utm.to_latlon(neg_bd[:,0], neg_bd[:,1], zone, 'R')

In [31]:
a = np.vstack((gps_x,gps_y))

In [32]:
np.transpose(a)

array([[ 25.08219767, 121.60394957],
       [ 25.08220679, 121.60395939],
       [ 25.0822067 , 121.60394947]])

In [33]:
np.sqrt(2)

1.4142135623730951

In [34]:
import geopandas as gpd

ModuleNotFoundError: No module named 'geopandas'

In [2]:
import shapefile

In [115]:
w = shapefile.Writer('/home/ncslaber/shapefiles/test/dtype')

In [110]:
w.field('LAT_LON', 'N', decimal=5)

In [103]:
b = np.transpose(a)

In [105]:
np.vstack((b,[ 25.08219767, 121.60394957]))

array([[ 25.08219767, 121.60394957],
       [ 25.08220679, 121.60395939],
       [ 25.0822067 , 121.60394947],
       [ 25.08219767, 121.60394957]])

In [92]:
lat = [25.1, 25.2, 25.3, 25.1]
lng = [122.1, 122.2, 122.3]

In [108]:
b.tolist()

array([[ 25.08219767, 121.60394957],
       [ 25.08220679, 121.60395939],
       [ 25.0822067 , 121.60394947]])

In [111]:
w.poly(b.tolist())
w.record('polygon1')
w.close()

Exception ignored in: <function Writer.__del__ at 0x7f9f9699ba60>
Traceback (most recent call last):
  File "/home/ncslaber/.local/lib/python3.8/site-packages/shapefile.py", line 1399, in __del__
    self.close()
  File "/home/ncslaber/.local/lib/python3.8/site-packages/shapefile.py", line 1415, in close
    raise ShapefileException("When saving both the dbf and shp file, "
shapefile.ShapefileException: When saving both the dbf and shp file, the number of records (2) must correspond with the number of shapes (0)


TypeError: 'float' object is not iterable

In [136]:
r = shapefile.Reader('/home/ncslaber/shapefiles/test/neg_1')

In [141]:
assert r.record(0)

In [116]:
w.field('name', 'C')

In [117]:
w.poly([
       [[113,24], [112,32], [117,36], [122,37], [118,20]], # poly 1
      [[116,29],[116,26],[119,29],[119,32]], # hole 1
        [[15,2], [17,6], [22,7]]  # poly 2
      ])

In [118]:
w.record('polygon1')

In [125]:
np.pi

3.141592653589793

In [135]:
np.sin(-np.pi/6)

-0.49999999999999994

In [129]:
b

array([[ 25.08219767, 121.60394957],
       [ 25.08220679, 121.60395939],
       [ 25.0822067 , 121.60394947]])

In [133]:
w = shapefile.Writer('/home/ncslaber/shapefiles/test/multipointSb')
w.field('name', 'C', '40')
w.multipoint(b) 
w.record('multipoint1')
w.close()

In [ ]:
w = shapefile.Writer('/home/ncslaber/shapefiles/test/dtype')
w.field('LAT', 'N', decimal=5)
w.field('LON', 'N', decimal=5)
w.null()
w.record(lat,lon)
w.close()

In [143]:
AA = np.load('/home/ncslaber/pos_traj_GPS.npy')

In [145]:
w = shapefile.Writer('/home/ncslaber/shapefiles/test/pos')
w.field('LAT_LON', 'C', '40')
w.multipoint(AA) 
w.record('pos')
w.close()

In [4]:
a = "/home/ncslaber/anny/pos"
a.split('/')[-3]

'ncslaber'

In [5]:
a.split('/')

['', 'home', 'ncslaber', 'anny', 'pos']

In [7]:
import csv
with open('/home/ncslaber/lat_lon.csv', 'a+') as csvfile: # or w
    writer = csv.writer(csvfile)
    writer.writerows([[25.0821685],[121.60401633333]])

In [8]:
with open('/home/ncslaber/lat_lon.csv', 'r') as csvfile:
    lat, lng = csv.reader(csvfile, delimiter=',')

In [15]:
lng = float(lng[0])

In [16]:
lng

121.60401633333

In [22]:
neg_bd = np.load('/home/ncslaber/shapefiles/test/utm_neg/neg1_bd_utm.npy')

In [26]:
utm.to_latlon(neg_bd[:,0], neg_bd[:,1], 51, 'R')

(array([25.08220337, 25.08220562, 25.08220726, 25.08220784, 25.08220721,
        25.08220554, 25.08220328, 25.08220103, 25.08219939, 25.08219881,
        25.08219944, 25.08220111]),
 array([121.60396137, 121.60396068, 121.60395885, 121.60395636,
        121.60395389, 121.60395209, 121.60395145, 121.60395214,
        121.60395398, 121.60395646, 121.60395893, 121.60396073]))

In [35]:
r = shapefile.Reader('/home/ncslaber/shapefiles/test/pos/pos_Dahu_enlarge')
# for shaperec in r.iterShapeRecords():
#     print(shaperec.shape)
#     pos_bd = shaperec.shape(0)
#     print(pos_bd(0))
#     print("---")
# pos_bd = r.record(0)
a = r.shape(0).points

In [36]:
a = np.asarray(a)

In [37]:
a[:,0]

array([25.08217079, 25.08217767, 25.08218137, 25.08218667, 25.08219249,
       25.08219777, 25.08220196, 25.08220454, 25.08220766, 25.08221226,
       25.08221472, 25.08221389, 25.08221258, 25.08220795, 25.08220444,
       25.082201  , 25.08219807, 25.08219409, 25.08218903, 25.08218281,
       25.08217713, 25.08217092, 25.08215979, 25.08214714, 25.08214494,
       25.0821346 , 25.08213351, 25.08212485, 25.08212431, 25.08211302,
       25.08210607, 25.08210071, 25.08209698, 25.08209274, 25.08209183,
       25.08209049, 25.08208685, 25.08208597, 25.08208615, 25.0820853 ,
       25.0820838 , 25.08208418, 25.08208655, 25.08208724, 25.08209081,
       25.08209476, 25.08209807, 25.08210246, 25.08210827, 25.08211247,
       25.08211698, 25.0821176 , 25.08212042, 25.08212386, 25.08212731,
       25.08212734, 25.08212849, 25.08213577, 25.082144  , 25.0821505 ,
       25.08216128, 25.08216611, 25.08216819, 25.08217079])

In [38]:
1024/3*2

682.6666666666666